#!/bin/bash

hour=0
min=25
sec=59

start() {
while [ $hour -ge 0 ]; do
       while [ $min -ge 0 ]; do
               while [ $sec -ge 0 ]; do
                        echo "$min:$sec"
                       let "sec=sec-1"
                       sleep 1
               done

               sec=59
               let "min=min-1"
        done
        min=59
        let "hour=hour-1"
done
}

start

