#!/usr/bin/bash

start(){
        echo "START"
}

pause(){
        echo "PAUSE"
}

stop() {
        echo "STOOOP"
}
increase(){
        echo "INCREASE"
}

decrease(){
        echo "DECREASE"
}

case "$BLOCK_BUTTON" in
        5) decrease ;;
        4) increase ;;
        3) stop ;;
        1) start ;;
        2) pause ;;
        
esac
echo "_"
